import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Head from "next/head";
import React from "react";

const articles = () => {
  return (
    <>
      <Head>
        <suppressHydrationWarning />
        <title>Article</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Layout className="pt16">
          <AnimatedText text=" Words Can Change The World!" className="mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl" />
        </Layout>
      </main>
    </>
  );
};

export default articles;
